ETrade.UI/Controllers/AuthController.cs
using ETrade.Ent;
using ETrade.UI.Session;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class AuthController : BaseController
    {
        private readonly Users user;

        public AuthController(IUow uow, Users user) : base(uow)
        {
            this.user = user;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(Users u)
        {
            uow.UserRepository.Register(u);
            uow.Commit();
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            return View(user);
        }

        [HttpPost]
        public IActionResult Login(Users u)
        {
            var loginUser = uow.UserRepository.Login(u);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "user", loginUser);
            SessionData.LoginUser = loginUser;
            if (SessionData.LoginUser.isAdmin == true)
            {
                return RedirectToAction("Admin", "Admin");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Logout()
        {
            Users users = null;
            SessionHelper.SetObjectAsJson(HttpContext.Session, "user", user);
            SessionData.LoginUser = SessionHelper.GetObjectFromJson<Users>(HttpContext.Session, "user");
            return RedirectToAction("Index", "Home");
        }
    }
}

ETrade.UI/Controllers/CategoriesController.cs
using ETrade.UI.Models.ViewModel;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class CategoriesController : BaseController
    {
        private readonly CategoriesModel model;

        public CategoriesController(IUow uow, CategoriesModel model) : base(uow)
        {
            this.model = model;
        }

        public IActionResult List()
        {
            return View(uow.CategoryRepository.GetCategories());
        }

        public IActionResult Create()
        {
            model.Text = "Save";
            model.Head = "New Categories";
            model.Class = "btn btn-outline-success my-2";

            return View("Crud", model);
        }

        [HttpPost]
        public IActionResult Create(CategoriesModel model)
        {
            uow.CategoryRepository.Add(model.Categories);
            uow.Commit();
            return RedirectToAction("List");
        }

        public IActionResult Update(Guid Id)
        {
            model.Text = "Save";
            model.Head = "Update Categories";
            model.Class = "btn btn-outline-success my-2";
            model.Categories = uow.CategoryRepository.Find(Id);

            return View("Crud", model);
        }

        [HttpPost]
        public IActionResult Update(CategoriesModel model)
        {
            uow.CategoryRepository.Update(model.Categories);
            uow.Commit();
            return RedirectToAction("List");
        }

        public IActionResult Delete(Guid Id)
        {
            uow.CategoryRepository.Delete(uow.CategoryRepository.Find(Id));
            uow.Commit();
            return RedirectToAction("List");
        }
    }
}

ETrade.UI/Controllers/OrdersController.cs
using ETrade.Ent;
using ETrade.UI.Session;
using ETrade.UOW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class OrdersController : BaseController
    {
        private readonly Orders orders;

        public OrdersController(IUow uow, Orders orders) : base(uow)
        {
            this.orders = orders;
        }

        public IActionResult List()
        {
            Guid Id = SessionData.LoginUser.UserId;
            return View(uow.OrderRepository.GetOrders(Id));
        }

        public IActionResult Create()
        {
            orders.isDelivered = false;
            orders.TotalPrice = 0;
            orders.UpdatedAt = DateTime.Now;
            SessionData.LoginUser = SessionHelper.GetObjectFromJson<Users>(HttpContext.Session, "user");
            orders.UserId = SessionData.LoginUser.UserId;
            orders.ShippingAddress = SessionData.LoginUser.ShippingAddress;
            orders.CreatedAt = DateTime.Now;
            uow.OrderRepository.Add(orders);
            uow.Commit();
            return RedirectToAction("List", "OrderDetails", new { Id = orders.OrderId });
        }
    }
}

ETrade.UI/Views/Shared/_Layout.cshtml
@using ETrade.UI.Session
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETrade.UI</title>
    @*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />*@
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        function showDropdown() {
            var toggleNavbar = document.getElementById("navbarToggle");
            var toggleNavbar = document.getElementById("navbarToggle2");
            navbarToggle.classList.toggle("opacity-0");
            navbarToggle.classList.toggle("opacity-100");
            navbarToggle.classList.toggle("hidden");
            navbarToggle.classList.toggle("block");
            navbarToggle2.classList.toggle("opacity-0");
            navbarToggle2.classList.toggle("opacity-100");
            navbarToggle2.classList.toggle("hidden");
            navbarToggle2.classList.toggle("block");
        };
    </script>
</head>
<body>
    <header>
        <nav class="flex justify-between bg-neutral-900 text-neutral-100">
            <div class="px-5 xl:px-12 py-6 flex w-full items-center">
                <a to="/" class="text-3xl font-bold font-heading">
                    <img class="h-9" src="~/logo.png" alt="logo" />
                </a>
                <ul class="hidden md:flex px-4 mx-auto font-semibold font-heading space-x-12">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index"
                           class="px-3 py-2 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg">
                            Home
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Categories" asp-action="List"
                           class="px-3 py-2 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg">
                            Categories
                        </a>
                    </li>
                </ul>
                <div class="hidden xl:flex items-center space-x-5">
                    <a class="hover:text-neutral-200" href="/liked"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" class="h-6 w-6"><path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z"></path></svg></a>
                    <a class="flex items-center hover:text-neutral-200" href="/sepet">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" class="h-6 w-6"><path fill-rule="evenodd" d="M7.5 6v.75H5.513c-.96 0-1.764.724-1.865 1.679l-1.263 12A1.875 1.875 0 004.25 22.5h15.5a1.875 1.875 0 001.865-2.071l-1.263-12a1.875 1.875 0 00-1.865-1.679H16.5V6a4.5 4.5 0 10-9 0zM12 3a3 3 0 00-3 3v.75h6V6a3 3 0 00-3-3zm-3 8.25a3 3 0 106 0v-.75a.75.75 0 011.5 0v.75a4.5 4.5 0 11-9 0v-.75a.75.75 0 011.5 0v.75z" clip-rule="evenodd"></path></svg>
                        <span class="flex absolute place-content-center -mt-5 ml-4"><span class="animate-ping absolute top-[2px] inline-flex h-3 w-3 rounded-full bg-orange-400 opacity-75"></span><span class="relative inline-flex rounded-full h-4 w-4 bg-orange-500 text-[9px] place-items-center place-content-center font-bold">0</span></span>
                    </a>
                    @if (!string.IsNullOrEmpty(SessionData.LoginUser.UserName))
                                    {<button onclick="showDropdown()" class="flex flex-col relative">
                        <div class="flex place-items-center">
                            <img class="h-8 w-8 rounded-full"
                                 src="https://randomuser.me/api/portraits/men/25.jpg"
                                 alt="" />
                            <div class="ml-3">
                                <p class="text-sm text-left font-medium text-neutral-100">
                                    
                                        @SessionData.LoginUser.UserName
                                    
                                </p>
                                <p class="text-sm text-slate-500 truncate">
                                    @SessionData.LoginUser.Mail
                                </p>
                            </div>
                        </div>
                        <ul id="navbarToggle" class="w-full hidden opacity-0 transition-opacity  duration-300 ease-in-out absolute p-2 top-10 shadow-xl overflow-hidden rounded-lg z-10 text-neutral-900 bg-neutral-100">
                                @if (SessionData.LoginUser.isAdmin == true)
                                {
                            <li>
                                <a asp-area="" asp-controller="Admin" asp-action="Admin"
                                   class="py-2 px-6 text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                                        Admin Dashboard
                                </a>
                            </li>
                                }
                                <li>
                            <a asp-area="" asp-controller="Orders" asp-action="List"
                               class="p-2 text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                                Siparişlerim
                                    </a>
                                </li>
<li>
                            <a asp-area="" asp-controller="Auth" asp-action="Logout" class="p-2 text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                                Logout

                                 </a></li>
                        </ul>
                    </button>
                    }else{
                        <a asp-area="" asp-controller="Auth" asp-action="Login"
                       class="px-3 py-2 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg">
                            Login
                        </a>
                        <a asp-area="" asp-controller="Auth" asp-action="Register"
                       class="px-3 py-2 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg">
                            Register
                        </a>
                    }
                </div>
            </div>
            <a class="xl:hidden flex mr-6 items-center" href="/sepet"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" class="h-6 w-6 hover:text-neutral-200"><path fill-rule="evenodd" d="M7.5 6v.75H5.513c-.96 0-1.764.724-1.865 1.679l-1.263 12A1.875 1.875 0 004.25 22.5h15.5a1.875 1.875 0 001.865-2.071l-1.263-12a1.875 1.875 0 00-1.865-1.679H16.5V6a4.5 4.5 0 10-9 0zM12 3a3 3 0 00-3 3v.75h6V6a3 3 0 00-3-3zm-3 8.25a3 3 0 106 0v-.75a.75.75 0 011.5 0v.75a4.5 4.5 0 11-9 0v-.75a.75.75 0 011.5 0v.75z" clip-rule="evenodd"></path></svg><span class="flex absolute -mt-5 ml-4"><span class="animate-ping absolute inline-flex h-3 w-3 rounded-full bg-orange-400 opacity-75"></span><span class="relative inline-flex rounded-full h-3 w-3 bg-orange-500 place-content-center font-bold text-[9px]">0</span></span></a>
            <div class="navbar-burger self-center mr-12 xl:hidden">
                @if (!string.IsNullOrEmpty(SessionData.LoginUser.UserName)){
                <button onclick="showDropdown()" class="flex flex-col relative">
                    <div class="flex place-items-center">
                        <img class="w-8 rounded-full"
                             src="https://randomuser.me/api/portraits/men/25.jpg"
                             alt="" />
                    </div>

                    <ul id="navbarToggle2"
                        class="hidden opacity-0 transition-opacity duration-300 ease-in-out min-w-max absolute p-2 right-0 top-10 shadow-xl overflow-hidden rounded-lg z-10 text-neutral-900 bg-neutral-100">
                        <li>
                            <div class="mb-3 py-2 px-6  rounded block bg-neutral-900 text-neutral-100">
                                <p class="text-xs text-left font-bold text-neutral-100">
                                        @SessionData.LoginUser.UserName
                                </p>
                                <p class="text-xs text-slate-500 truncate">
                                        @SessionData.LoginUser.Mail
                                </p>
                            </div>
                        </li>
                            @if (SessionData.LoginUser.isAdmin ==true)
                            {
                        <li>
                            <a asp-area="" asp-controller="Admin" asp-action="Admin"
                               class="py-2 px-6 text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                                Admin Dashboard
                            </a>
                        </li>}
                        <li>
                            <a asp-area="" asp-controller="Orders" asp-action="List"
                               class="py-2 px-6 text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                                Siparişlerim
                            </a>
                        </li>
                        <li class="py-2 px-6 text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                            <a to="liked" class="hover:text-neutral-200">
                                Favoriler
                            </a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Auth" asp-action="Logout" class="p-2 px-6  text-sm rounded block hover:bg-neutral-900 hover:text-neutral-100">
                                Logout
                            </a>
                        </li>
                    </ul>
                </button>
                }else{
                    <a asp-area="" asp-controller="Auth" asp-action="Login"
                       class="px-3 py-2 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg">
                            Login
                        </a>
                        <a asp-area="" asp-controller="Auth" asp-action="Register"
                       class="px-3 py-2 hover:text-neutral-200 hover:bg-neutral-800 rounded-lg">
                            Register
                        </a>
                }
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 hover:text-neutral-200">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>

            </div>
        </nav>
    </header>
    <div class="container mx-auto">
        <main role="main" class="pb-3">
            <div class="container w-full mx-auto p-4">
                    @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>